# Generated by Django 4.1.2 on 2023-02-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_softwarepackage_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
